---
detectors:
  IrresponsibleModule:
    enabled: false

  UtilityFunction:
    enabled: false # TODO: Remove this line
    public_methods_only: true
    exclude:
      - "#authorize"

  FeatureEnvy:
    enabled: false

  ControlParameter:
    enabled: false

exclude_paths:
  - vendor/bundle
  - db/migrate